/**
 * Members Application — form configuration built in the admin panel.
 *
 * One template per application type. Drafts are invisible to applicants; at most
 * one template per formType is published at a time, and publishing a new one
 * supersedes the previous (see routes/members/forms.js).
 */

const mongoose = require('mongoose');
const membersConnection = require('../../config/membersConnection');
const { pageSchema } = require('./formSchemas');

const FORM_TYPES = ['rukn', 'karkoon'];

const formTemplateSchema = new mongoose.Schema({
  formType: {
    type: String,
    enum: FORM_TYPES,
    required: true,
    index: true
  },
  title: {
    type: String,
    required: true,
    trim: true,
    maxlength: 300
  },
  description: {
    type: String,
    default: '',
    maxlength: 2000
  },
  pages: [pageSchema],
  version: {
    type: Number,
    default: 1
  },
  isPublished: {
    type: Boolean,
    default: false
  },
  publishedAt: {
    type: Date,
    default: null
  },
  isActive: {
    type: Boolean,
    default: true
  },
  // Marks templates generated by scripts/migrateMembersFromJih.js so that
  // imported legacy submissions still render.
  isLegacyImport: {
    type: Boolean,
    default: false
  },
  createdBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'MemberAdmin',
    default: null
  },
  updatedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'MemberAdmin',
    default: null
  }
}, { timestamps: true });

formTemplateSchema.index({ formType: 1, isPublished: 1, isActive: 1 });
formTemplateSchema.index({ createdAt: -1 });

module.exports = membersConnection.model('FormTemplate', formTemplateSchema);
module.exports.FORM_TYPES = FORM_TYPES;
